TARGET_EXEC := opencv_test

BUILD_DIR := ./build
INC_DIRS := ./include
SRC_DIRS := ./src

OPENCV_DIR := C:/opencv/install

SRCS := $(shell find $(SRC_DIRS) -name *.cpp)
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)

MANUAL_INC_DIRS := $(OPENCV_DIR)/include
INC_DIRS := $(OPENCV_DIR)/include $(shell find $(INC_DIRS) -type d)
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

LIB_DIRS := $(OPENCV_DIR)/x64/mingw/lib $(OPENCV_DIR)/x64/mingw/bin
LIB_FLAGS := $(addprefix -L,$(LIB_DIRS))

LDFLAGS := $(LIB_FLAGS) -lopencv_core490 -lopencv_imgcodecs490

CXX := g++
CPPFLAGS := $(INC_FLAGS) -Wall -Wextra -g

$(BUILD_DIR)/$(TARGET_EXEC): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)

$(BUILD_DIR)/%.cpp.o: %.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) -c $< -o $@ $(LDFLAGS)

test:
	@echo $(SRCS)
	@echo $(OBJS)
	@echo $(INC_DIRS)
	@echo $(INC_FLAGS)

run:
	@./$(BUILD_DIR)/$(TARGET_EXEC)

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)
